
palette = "kanagawa-lotus"

[palettes.kanagawa-lotus]
bg0 = '#f2ecbc'
bg1 = '#e7dba0'
fg = '#545464'
red = '#c84053'
orange = '#cc6d00'
yellow = '#77713f'
green = '#6f894e'
aqua = '#597b75'
blue = '#4d699b'
purple = '#b35b79'
