
palette = "everforest-dark"

[palettes.everforest-dark]
bg0 = '#272E33'
bg1 = '#2E383C'
fg = '#D3C6AA'
red = '#E67E80'
orange = '#E69875'
yellow = '#DBBC7F'
green = '#A7C080'
aqua = '#83C092'
blue = '#7FBBB3'
purple = '#D699B6'
