
palette = "kanagawa-wave"

[palettes.kanagawa-wave]
bg0 = '#2B2A27'
bg1 = '#1E1D1B'
fg = '#DCD7BA'
red = '#C34043'
orange = '#FFA066'
yellow = '#E6C384'
green = '#98BB6C'
aqua = '#7AA89F'
blue = '#7E9CD8'
purple = '#957FB8'
