
palette = "everforest-light"

[palettes.everforest-light]
bg0 = '#FFFBEF'
bg1 = '#F8F5E4'
fg = '#5C6A72'
red = '#F85552'
orange = '#F57D26'
yellow = '#DFA000'
green = '#8DA101'
aqua = '#35A77C'
blue = '#3A94C5'
purple = '#DF69BA'
