
palette = "modus_operandi"

[palettes.modus_operandi]
bg        = "#ffffff"
float     = "#f2f2f2"
sel       = "#dfa0f0"
ui        = "#646464"
com       = "#7f0000"
fg        = "#000000"
red       = "#a60000"
yellow    = "#6f5500"
green     = "#006800"
cyan      = "#005e8b"
blue      = "#3548cf"
magenta   = "#721045"
red_alt   = "#7f0000"
yellow_alt = "#884900"
green_alt = "#0f7f5f"
cyan_alt  = "#1f6fbf"
blue_alt  = "#0031a9"
magenta_alt = "#531ab6"
