
palette = "modus_vivendi"

[palettes.modus_vivendi]
bg        = "#000000"
float     = "#1e1e1e"
sel       = "#7030af"
ui        = "#646464"
com       = "#ff9f80"
fg        = "#ffffff"
red       = "#ff5f59"
yellow    = "#d0bc00"
green     = "#44bc44"
cyan      = "#00d3d0"
blue      = "#79a8ff"
magenta   = "#feacd0"
red_alt   = "#ff9f80"
yellow_alt = "#fec43f"
green_alt = "#00c06f"
cyan_alt  = "#6ae4b9"
blue_alt  = "#2fafff"
magenta_alt = "#b6a0ff"
