
palette = "modus_operandi_tinted"

[palettes.modus_operandi_tinted]
bg        = "#fbf7f0"
float     = "#e0d6c0"
sel       = "#dfa0f0"
ui        = "#cab9b2"
com       = "#7f0000"
fg        = "#000000"
red       = "#a60000"
yellow    = "#6f5500"
green     = "#006800"
cyan      = "#005e8b"
blue      = "#3548cf"
magenta   = "#721045"
red_alt   = "#7f0000"
yellow_alt = "#884900"
green_alt = "#0f7f5f"
cyan_alt  = "#1f6fbf"
blue_alt  = "#0031a9"
magenta_alt = "#531ab6"
